modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "https://github.com/liquidcatmofu/Resource-Reload-Guard/issues"
license = "MIT"

[[mods]]
modId = "resource_reload_guard"
version = "${version}"
displayName = "Resource Reload Guard"
displayURL = "https://github.com/liquidcatmofu/Resource-Reload-Guard"
authors = "LiquidCatMofu"
logoFile = "assets/resource_reload_guard/icon.png"
description = '''
Guards expensive client resource reloads triggered by user actions.
'''

[[dependencies.resource_reload_guard]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.resource_reload_guard]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "resource_reload_guard.mixins.json"
